image:
  repository: us-central1-docker.pkg.dev/terraform-project-akhasa1/docker-registry/dev-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.0.0"

ingress:
  enabled: true
  className: "nginx"
  annotations: 
      ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/cluster-issuer: letsencrypt-dev
      acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: dev-app.adilet-khasanov.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: chart-example-tls
     hosts:
       - dev-app.adilet-khasanov.net